### ISSUE TITLE
Add logos for sponsors 

### ISSUE THREAD

**Issue by Aniket965** [IntelAISociety/intelaisociety.github.io#13]
- [x] progate
- [x] eckovation
- [x] hackerank
- [x] o'reilly

**Comment by Aniket965** [comment]
two step process add div in container grid and add image in background using n-th-child selector

**Comment by Aniket965** [comment]
https://github.com/IntelAISociety/intelaisociety.github.io/blob/613c033789a0e95878ccb91cb7e59780f9ff0012/index.html#L114 you will have to add new linke this one and add logo of these companies in img folder then you can add https://github.com/IntelAISociety/intelaisociety.github.io/blob/613c033789a0e95878ccb91cb7e59780f9ff0012/css/style.css#L585 the image url in css like this line its easy you can check other how we added others logos for refrence

**Comment by Aniket965** [comment]
its solved

**Comment by Ishaan28malik** [comment]
ok
