### ISSUE TITLE
Create a better nav bar for mobile view

### ISSUE THREAD

**Issue by Aniket965** [IntelAISociety/intelaisociety.github.io#14]
- The current
![asd](https://user-images.githubusercontent.com/22680912/46366983-1b4b8f00-c69a-11e8-9892-1e855b1026d7.jpg)
 nav bar is not that convenient to navigate between sections.

**Comment by Jaammeesss** [comment]
i'll take a look at this

**Comment by Aniket965** [comment]
Sure!

**Comment by Aniket965** [comment]
solved
