### ISSUE TITLE
Add Link to our event site 

### ISSUE THREAD

**Issue by Aniket965** [IntelAISociety/intelaisociety.github.io#6]
- [x] http://intelevents.ml in event section

**Comment by akshitac8** [comment]
Can you give details on this

**Comment by akshitac8** [comment]
Does the content displayed on http://intelevents.ml have to displayed when clicked on events link?

**Comment by mukulgoyal40** [comment]
Same question, please elaborate the issue.

**Comment by Aniket965** [comment]
we need to add a hyper link to this site in event section

**Comment by Aniket965** [comment]
fixed thanks to @akshitac8
